apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: pvc-36078537-e14f-4383-b46c-7872a914c852
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 25Gi
  mountOptions:
    - nolock
    - soft
    - rw
  nfs:
    path: /export/PersistentVolumes1/audiobookshelf-audiobookshelf-metadata-pvc-36078537-e14f-4383-b46c-7872a914c852
    server: 10.0.0.195
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem
