apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: pvc-ad5bb197-dbee-4cc4-b5fb-cfc0de0f2ae1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  mountOptions:
    - nolock
    - soft
    - rw
  nfs:
    path: /export/PersistentVolumes1/audiobookshelf-audiobookshelf-audiobooks-pvc-ad5bb197-dbee-4cc4-b5fb-cfc0de0f2ae1
    server: 10.0.0.195
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem

