apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-creds
type: Opaque
stringData:
  MINIO_USER: "admin"
  MINIO_PASSWORD: "<password>"

---

apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-daily
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres