apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: swarm-ui
  name: swarm-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swarm-ui
  template:
    metadata:
      labels:
        app: swarm-ui
    spec:
      serviceAccountName: swarm-ui
      dnsConfig:
        nameservers:
          - 1.1.1.1
      containers:
        - image: "{{ .Values.image.registry }}/swarmui:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: swarm-ui
          env:
            - name: LANG
              value: en_US.utf8
            - name: TZ
              value: {{ .Values.service.timezone }}
            - name: PATH
              value: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin
          volumeMounts:
            - name: swarm-ui
              mountPath: /SwarmUI
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "8"
              memory: "24Gi"
              nvidia.com/gpu: 1
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - name: swarm-ui
          persistentVolumeClaim:
            claimName: swarm-ui